Crews-Server/crews-server

post/serializers.py, post/views.py
=> :bug: PostContent_PostSerializer 내 필드에 progress 필드 추가 (#5)

post/serializers.py, table/models.py, table/serializers.py
=> PostContent_PostSerializer에서 total_likes, total_applies 값을 가져올 수 있도록 기능 강화하기

mypage/serializers.py, mypage/urls.py, mypage/views.py
가장 기본적으로 마이 페이지 들어갔을 때 맨 위 기본 정보 띄워주는 api.
=> 마이페이지 들어갔을 때 기본 정보 띄워 주기

table/admin.py, table/models.py, table/serializers.py, table/urls.py, table/views.py
=> Comment 랑 Score 모델 추가

accounts/serializers.py, accounts/urls.py, accounts/views.py, config/settings.py, table/models.py
JWT 토큰 기반으로 회원가입/로그인 기능을 완성하였습니다.
회원가입 http://127.0.0.1:8000/accounts/register/
- 회원가입시에는 body에 email, name, password, sogang_mail, student_number, first_major 정보를 다 넣어주셔야지
정상적으로 회원가입이 됩니다!
로그인 http://127.0.0.1:8000/accounts/login/
- 로그인시에는 body에 email과 password를 입력하면 가능합니다!
- 정상적으로 로그인이 되었을 때 access토큰과 refresh 토큰을 반환합니다.
=> 로그인 / 회원가입 기능 개발 완료

accounts/urls.py, accounts/views.py
google 계정을 기반으로 클라이언트로부터 회원가입하려는 이용자의 서강 메일에 관한
중복 체크 및 인증번호가 담긴 메일을 보내 인증을 처리하는 로직의 api를 개발하였습니다.
=> :sparkles: 서강메일 인증 확인하는 sogang_mail_check view 완성 (#18)

accounts/views.py
=> :bug: 주석 오타 수정

accounts/views.py
sogang_mail_check view 내에서 
사용자로부터 입력받은 서강 이메일이 정말로 @sogang.ac.kr로 끝나는 서강대학교 이메일이 맞는지
확인하는 로직을 추가하였습니다. 
이를 통해 서강대 계정을 넣어야 하는데 네이버, 구글 등 다른 메일 계정을 넣음으로써 서강계정 인증을 회피하는 것을
막을 수 있습니다.
=> :sparkles: @sogang.ac.kr로 끝나는지 체크하는 기능 추가 (#18)

table/models.py
=> :bug: Like 모델 내 __str__ 버그 수정 (#1)

post/views.py
=> :bug: post_id 변수명 수정 (#5)

mypage/serializers.py, mypage/urls.py, mypage/views.py
일반 유저가 자신의 마이페이지에 접속했을 때, 자신이 찜한 Post 목록을 반환해주는 api입니다.
=> 일반 유저의 마이페이지에서 찜한 모집 공고 리스트 반환해주는 api 구현하기

table/models.py
=> :bug: Apply table 버그 수정 (#1)

mypage/serializers.py, mypage/urls.py, mypage/views.py
일반 유저가 자신의 마이페이지에 접속했을 때 본인이 지원한 동아리 리스트를 반환해주는 api 입니다.
=> :sparkles: 일반 유저의 마이페이지에서 본인이 지원한 동아리 리스트 반환해주는 api 개발 완료 (#6)

table/models.py
=> Evaluation 모델 추가 (#1)

table/models.py
=> :bug: Evaluation 모델 수정  (#1)

mypage/serializers.py, mypage/urls.py, mypage/views.py
=> :sparkles: get_crews_posts 뷰 완성, url처리 (#6)

mypage/serializers.py, mypage/views.py
=> :bug: mypage 앱 내부 버그 수정 + 주석 수정 (#6)

mypage/serializers.py, mypage/views.py, requirements.txt
=> :bug: get_applied_list 버튼 관련 버그 수정 완료 (#6)

mypage/serializers.py, mypage/views.py
=> :bug: mypage 관련 api들 버그 전부 수정하기 (#6)

mypage/urls.py, mypage/views.py
=> :sparkles: 1~5번 api 내용 한번에 보내주는 all-in-one api 만들기 (#6)

requirements.txt
=> :sparkles: requirement.txt 업데이트  (#1)

accounts/models.py, home/serializers.py, home/urls.py, home/views.py, mypage/views.py
=> :sparkles: 메인페이지 모든 구현 완료 (#44)

config/settings.py, table/models.py
> aws s3 저장소를 연동하여 사진, 파일 등을 aws로 관리합니다.
=> :sparkles: aws s3 저장소 연동하기 (#1)

requirements.txt
=> requirements.txt 수정  (#1)

accounts/views.py
=> accounts앱 내에 클라우트 타입 배포를 위한 get_env 삭제 부분 반영 (#1)

config/settings.py
=> csrf 세팅 반영  (#1)

accounts/views.py, config/settings.py, requirements.txt
=> 배포 전 단계 완료 모든 버그 수정 (#1)

config/settings.py
=> 배포 전 단계 완료 모든 버그 수정 22 (#1)

accounts/views.py, config/settings.py, post/serializers.py, post/views.py
=> :bug: post앱 3번 api 수정  (#5)

post/serializers.py
=> :bug: 다시 수정 (#5)

config/settings.py
=> :sparkles: csrf 버셀 링크 추가 (#1)

accounts/serializers.py, accounts/views.py
=> 로그인 시 반환 값들 조정하는 코드 만들기  (#1)

post/serializers.py, post/views.py
=> post 1번 뷰 수정 (#1)
